echo 'SERVICE + PORTS '
echo -e '\n'
sudo docker ps --format '{{.Names}}\t{{.Ports}}' | grep -oE '[^[:space:]]+\s+0\.0\.0\.0:[0-9]+->[0-9]+' | awk '{split($2,a,":"); print $1, a[2]}'
echo -e '\n\n\n'
echo 'INTERNAL PORT -> EXTERNAL PORT'
echo -e '\n'
sudo docker ps --format '{{.Ports}}' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+->[0-9]+' | awk -F: '{print $2}'
echo -e '\n\n\n'
echo 'EXTERNAL PORT'
echo -e '\n'
sudo docker ps --format '{{.Ports}}' | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+:[0-9]+' | awk -F: '{print $2}'
